# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tonywu315/Github/chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tonywu315/Github/chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tonywu315/Github/chess/CMakeFiles /home/tonywu315/Github/chess//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tonywu315/Github/chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess.out

# Build rule for target.
chess.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chess.out
.PHONY : chess.out

# fast build rule for target.
chess.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/build
.PHONY : chess.out/fast

src/benchmark.o: src/benchmark.c.o
.PHONY : src/benchmark.o

# target to build an object file
src/benchmark.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/benchmark.c.o
.PHONY : src/benchmark.c.o

src/benchmark.i: src/benchmark.c.i
.PHONY : src/benchmark.i

# target to preprocess a source file
src/benchmark.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/benchmark.c.i
.PHONY : src/benchmark.c.i

src/benchmark.s: src/benchmark.c.s
.PHONY : src/benchmark.s

# target to generate assembly for a file
src/benchmark.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/benchmark.c.s
.PHONY : src/benchmark.c.s

src/board.o: src/board.c.o
.PHONY : src/board.o

# target to build an object file
src/board.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/board.c.o
.PHONY : src/board.c.o

src/board.i: src/board.c.i
.PHONY : src/board.i

# target to preprocess a source file
src/board.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/board.c.i
.PHONY : src/board.c.i

src/board.s: src/board.c.s
.PHONY : src/board.s

# target to generate assembly for a file
src/board.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/board.c.s
.PHONY : src/board.c.s

src/evaluation.o: src/evaluation.c.o
.PHONY : src/evaluation.o

# target to build an object file
src/evaluation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/evaluation.c.o
.PHONY : src/evaluation.c.o

src/evaluation.i: src/evaluation.c.i
.PHONY : src/evaluation.i

# target to preprocess a source file
src/evaluation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/evaluation.c.i
.PHONY : src/evaluation.c.i

src/evaluation.s: src/evaluation.c.s
.PHONY : src/evaluation.s

# target to generate assembly for a file
src/evaluation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/evaluation.c.s
.PHONY : src/evaluation.c.s

src/move.o: src/move.c.o
.PHONY : src/move.o

# target to build an object file
src/move.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/move.c.o
.PHONY : src/move.c.o

src/move.i: src/move.c.i
.PHONY : src/move.i

# target to preprocess a source file
src/move.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/move.c.i
.PHONY : src/move.c.i

src/move.s: src/move.c.s
.PHONY : src/move.s

# target to generate assembly for a file
src/move.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/move.c.s
.PHONY : src/move.c.s

src/move_generation.o: src/move_generation.c.o
.PHONY : src/move_generation.o

# target to build an object file
src/move_generation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/move_generation.c.o
.PHONY : src/move_generation.c.o

src/move_generation.i: src/move_generation.c.i
.PHONY : src/move_generation.i

# target to preprocess a source file
src/move_generation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/move_generation.c.i
.PHONY : src/move_generation.c.i

src/move_generation.s: src/move_generation.c.s
.PHONY : src/move_generation.s

# target to generate assembly for a file
src/move_generation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/move_generation.c.s
.PHONY : src/move_generation.c.s

src/search.o: src/search.c.o
.PHONY : src/search.o

# target to build an object file
src/search.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/search.c.o
.PHONY : src/search.c.o

src/search.i: src/search.c.i
.PHONY : src/search.i

# target to preprocess a source file
src/search.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/search.c.i
.PHONY : src/search.c.i

src/search.s: src/search.c.s
.PHONY : src/search.s

# target to generate assembly for a file
src/search.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/search.c.s
.PHONY : src/search.c.s

src/test.o: src/test.c.o
.PHONY : src/test.o

# target to build an object file
src/test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/test.c.o
.PHONY : src/test.c.o

src/test.i: src/test.c.i
.PHONY : src/test.i

# target to preprocess a source file
src/test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/test.c.i
.PHONY : src/test.c.i

src/test.s: src/test.c.s
.PHONY : src/test.s

# target to generate assembly for a file
src/test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.out.dir/build.make CMakeFiles/chess.out.dir/src/test.c.s
.PHONY : src/test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chess.out"
	@echo "... src/benchmark.o"
	@echo "... src/benchmark.i"
	@echo "... src/benchmark.s"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/evaluation.o"
	@echo "... src/evaluation.i"
	@echo "... src/evaluation.s"
	@echo "... src/move.o"
	@echo "... src/move.i"
	@echo "... src/move.s"
	@echo "... src/move_generation.o"
	@echo "... src/move_generation.i"
	@echo "... src/move_generation.s"
	@echo "... src/search.o"
	@echo "... src/search.i"
	@echo "... src/search.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

